# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 11:58
from __future__ import unicode_literals

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=300, null=True)),
                ('password', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=300, unique=True)),
                ('web_url', models.CharField(blank=True, max_length=300, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=company.models.get_vendor_image_path)),
                ('day_timings', models.CharField(blank=True, max_length=300, null=True)),
                ('op_timings', models.CharField(blank=True, max_length=300, null=True)),
                ('close_timings', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.CharField(blank=True, max_length=300, null=True)),
                ('cuisines', models.CharField(blank=True, max_length=300, null=True)),
                ('ambience', models.CharField(blank=True, max_length=300, null=True)),
                ('special_offerings', models.CharField(blank=True, max_length=300, null=True)),
                ('ordering_options', models.IntegerField(blank=True, null=True)),
                ('cost_for_two', models.CharField(blank=True, max_length=300, null=True)),
                ('payment_modes', models.CharField(blank=True, max_length=255, null=True)),
                ('facilities', models.CharField(blank=True, max_length=300, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=300, null=True)),
                ('phone_contact_person', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('is_anonymous', models.IntegerField(default=False)),
                ('is_active', models.IntegerField(default=1)),
                ('is_authenticated', models.IntegerField(default=False)),
                ('last_login', models.DateTimeField(default='1970-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='TblData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_type', models.CharField(blank=True, max_length=300, null=True)),
                ('cat_name', models.CharField(blank=True, max_length=300, null=True)),
                ('display_name', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=company.models.get_catagory_path)),
            ],
        ),
    ]
