# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 13:36
from __future__ import unicode_literals

import company.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=250, null=True)),
                ('password', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('web_url', models.CharField(blank=True, max_length=250, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_photo', models.FileField(blank=True, null=True, upload_to=company.models.get_vendor_image_path)),
                ('mon_op_timings', models.CharField(blank=True, max_length=250, null=True)),
                ('mon_close_timings', models.CharField(blank=True, max_length=250, null=True)),
                ('tues_op_timings', models.CharField(blank=True, max_length=250, null=True)),
                ('tues_close_timings', models.CharField(blank=True, max_length=250, null=True)),
                ('wed_op_timings', models.CharField(blank=True, max_length=250, null=True)),
                ('wed_close_timings', models.CharField(blank=True, max_length=250, null=True)),
                ('thurs_op_timings', models.CharField(blank=True, max_length=250, null=True)),
                ('thurs_close_timings', models.CharField(blank=True, max_length=250, null=True)),
                ('fri_op_timings', models.CharField(blank=True, max_length=250, null=True)),
                ('fri_close_timings', models.CharField(blank=True, max_length=250, null=True)),
                ('sat_op_timings', models.CharField(blank=True, max_length=250, null=True)),
                ('sat_close_timings', models.CharField(blank=True, max_length=250, null=True)),
                ('sun_op_timings', models.CharField(blank=True, max_length=250, null=True)),
                ('sun_close_timings', models.CharField(blank=True, max_length=250, null=True)),
                ('food_menu', models.FileField(blank=True, null=True, upload_to=company.models.get_food_menu_path)),
                ('drinks_menu', models.FileField(blank=True, null=True, upload_to=company.models.get_drinks_menu_path)),
                ('dessert_menu', models.FileField(blank=True, null=True, upload_to=company.models.get_dessert_menu_path)),
                ('cafe_menu', models.FileField(blank=True, null=True, upload_to=company.models.get_cafe_menu_path)),
                ('category', models.CharField(blank=True, max_length=250, null=True)),
                ('cuisines', models.CharField(blank=True, max_length=250, null=True)),
                ('ambience', models.CharField(blank=True, max_length=250, null=True)),
                ('special_offerings', models.CharField(blank=True, max_length=250, null=True)),
                ('ordering_options', models.IntegerField(blank=True, null=True)),
                ('cost_for_two', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_modes', models.CharField(blank=True, max_length=250, null=True)),
                ('facilities', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_contact_person', models.CharField(blank=True, max_length=250, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('is_anonymous', models.IntegerField(default=False)),
                ('is_active', models.IntegerField(default=1)),
                ('is_authenticated', models.IntegerField(default=False)),
                ('last_login', models.DateTimeField(default='1970-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='TblData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_type', models.CharField(blank=True, max_length=250, null=True)),
                ('cat_name', models.CharField(blank=True, max_length=250, null=True)),
                ('display_name', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=company.models.get_catagory_path)),
            ],
        ),
        migrations.CreateModel(
            name='TblVendorImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=company.models.get_vendor_image_path)),
                ('vendor', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
