# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20170718_1307'),
        ('company', '0002_auto_20170724_0701'),
    ]

    operations = [
    ]
