# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 12:38
from __future__ import unicode_literals

import company.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_merge_20170927_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblCoupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('coupon_id', models.CharField(blank=True, max_length=250, null=True)),
                ('display_name', models.CharField(blank=True, max_length=250, null=True)),
                ('discount', models.CharField(blank=True, max_length=250, null=True)),
                ('applicable_on', models.CharField(blank=True, max_length=250, null=True)),
                ('valid_for', models.CharField(blank=True, max_length=250, null=True)),
                ('valid_on_days', models.CharField(blank=True, max_length=250, null=True)),
                ('start_date', models.CharField(blank=True, max_length=250, null=True)),
                ('end_date', models.CharField(blank=True, max_length=250, null=True)),
                ('actual_price', models.CharField(blank=True, max_length=250, null=True)),
                ('offer_price', models.CharField(blank=True, max_length=250, null=True)),
                ('terms_conditions', models.CharField(blank=True, max_length=250, null=True)),
                ('special_offer_menus', models.FileField(blank=True, null=True, upload_to=company.models.get_special_offer_menu_path)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblHappyHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('happy_hour_id', models.CharField(blank=True, max_length=250, null=True)),
                ('display_name', models.CharField(blank=True, max_length=250, null=True)),
                ('start_time', models.CharField(blank=True, max_length=250, null=True)),
                ('end_time', models.CharField(blank=True, max_length=250, null=True)),
                ('discount', models.CharField(blank=True, max_length=250, null=True)),
                ('applicable_on', models.CharField(blank=True, max_length=250, null=True)),
                ('valid_for', models.CharField(blank=True, max_length=250, null=True)),
                ('valid_on_days', models.CharField(blank=True, max_length=250, null=True)),
                ('terms_conditions', models.CharField(blank=True, max_length=250, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblRepetetionDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=250, null=True)),
                ('start_time', models.CharField(blank=True, max_length=250, null=True)),
                ('end_time', models.CharField(blank=True, max_length=250, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('happy_hour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.TblHappyHours')),
            ],
        ),
        migrations.AlterField(
            model_name='tblvendor',
            name='cover_photo',
            field=models.FileField(blank=True, null=True, upload_to=company.models.get_vendor_image_path),
        ),
    ]
